# Change these first
owner: discohook # Your GitHub organization or username, where this repository lives
repo: statuspage # The name of this repository

sites:
  - name: Discohook.app
    url: https://discohook.app

status-website:
  cname: status.discohook.app
  logoUrl: https://github.com/discohook/discohook/raw/refs/heads/main/packages/site/public/logos/icon.svg
  name: Discohook
  # introTitle: "Discohook is a simple, free, and highly versatile message designer for Discord webhooks."
  introMessage: This page automatically monitors the uptime of discohook.app. In the future, bot incidents will also be posted here.
  theme: dark
  navbar:
    - title: Status
      href: /
    - title: Discord
      href: https://discord.gg/discohook-668218342779256857

workflowSchedule:
  # default is every 5 mins
  uptime: "*/10 * * * *"
